# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
# relative_permalinks: true

# Setup
title:               Sous Vide Data
tagline:             'Simple Sous Vide Data'
description:         'easily find sous vide shit'
url:                 http://www.blairanderson.co/sous-vide
baseurl:             ''
gems:                [jekyll-paginate, classifier-reborn]
paginate:            5

collections:
  guides:
    output: true
    permalink: /awesome/:path/
# About/contact
author:
  name:              Blair Anderson
  url:               https://twitter.com/blairanderson
  email:             blair81@gmail.com

# Custom vars
version:             1.0.0
